version: "3.9"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    hostname: "rabbitmq"
    ports:
      - "5672:5672" # default RabbitMQ port for AMQP (Advanced Message Queuing Protocol)  
      - "15672:15672" # RabbitMQ management port  
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
      - RABBITMQ_DEFAULT_VHOST=myvhost
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

volumes:
  rabbitmq_data: